### ISSUE TITLE
[CHECKLIST] Getting to Know the Job

### ISSUE THREAD

**Issue by handsfreemc** [handsfreemc/sourcing#2]
## Here are some ways to get to know the job you're sourcing for - both online and offline.

📝 You can view a printable PDF version of this list here.

## Online
- [ ] Job description
- [ ] Competitor's job description
- [ ] YouTube - conference talks, career profiles, day in the life videos
- [ ] Quora
- [ ] Twitter
- [ ] Google Alerts
- [ ] Feedback from profiles shared with hiring team
- [ ] Google News
- [ ] Test your Boolean strings against 'ideal' profiles or people in the role
- [ ] Keep track of search strings as your understanding of role evolves
- [ ] Vary emphasis of search
ex: title search, title plus must haves, company and must haves without title
- [ ] Interview feedback
- [ ] Notes from hiring team/interviewers
- [ ] Team blog/internal sites
- [ ] 

## Offline
- [ ] Strategy Session
- [ ] Post interview debrief/Hiring committee
- [ ] Follow up with candidate after interview
- [ ] Team calls (weekly) - phone/video conference
- [ ] Eventbrite/Meetup - any events worth attending with a member of the hiring team?
- [ ] Attend conferences
- [ ] Hiring Manager 1:1
- [ ] Speak with incumbent
- [ ] Peers in network with title
- [ ] Other recruiters/sourcers working similar roles
- [ ] Recent Hires
- [ ] Referrals
- [ ] Conversations with Active Applicants
- [ ] Screenings with Sourced Prospects - including those that don't have "ideal profiles"
- [ ] Team meetings (weekly or bi-weekly) - on site
- [ ] Active applicants in advanced stages
- [ ] Follow ups to initial strategy session
- [ ] 

Have a great idea to add? Post a comment and I will update the list!
